### ISSUE TITLE
Empty Active Directory Username not being caught

### ISSUE THREAD

**Issue by dogshapedangel** [pumpingstationone/WA2AD#1]
When a user's "Active Directory Username" is not filled out on Wild Apricot, WA2AD.exe crashes with the following message

`Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: Principal.SamAccountName cannot be null or empty.
   at System.DirectoryServices.AccountManagement.Principal.set_SamAccountName(String value)
   at WA2AD.ADActions.HandleMember(Member member) in C:\Users\Mituna\Downloads\WA2AD-master\WA2AD-master\ADActions
ne 111
   at WA2AD.Program..ctor() in C:\Users\Mituna\Downloads\WA2AD-master\WA2AD-master\Program.cs:line 23
   at WA2AD.Program.Main(String[] args) in C:\Users\Mituna\Downloads\WA2AD-master\WA2AD-master\Program.cs:line 31`

An ideal method of handling this would be to email admins when this happens. This should be a rare occurrence... But we should at least be catching it

**Comment by tachoknight** [comment]
Fixed in [4153f788](https://github.com/pumpingstationone/WA2AD/commit/4153f788fe07961214dd8c66bf41443e821385e4)
