### ISSUE TITLE
Unhandled exception - no membership assigned

### ISSUE THREAD

**Issue by dogshapedangel** [pumpingstationone/WA2AD#5]
We have a user that's failing who has no membership assigned

`Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at WA2AD.ADActions.HandleMember(Member member) in C:\Users\Mituna\Source\Repos\pumpingstationone\WA2AD\ADActions.cs:line 187
   at WA2AD.Program..ctor() in C:\Users\Mituna\Source\Repos\pumpingstationone\WA2AD\Program.cs:line 23
   at WA2AD.Program.Main(String[] args) in C:\Users\Mituna\Source\Repos\pumpingstationone\WA2AD\Program.cs:line 31`

**Comment by dogshapedangel** [comment]
Hm, it appears that it is trying to set the SamAccountName... the account has none and should probably be aborted when it finds a suspended membership with no existing account (edge case)

**Comment by tachoknight** [comment]
Fixed in [4153f788](https://github.com/pumpingstationone/WA2AD/commit/4153f788fe07961214dd8c66bf41443e821385e4)
